apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container 
        image: roytzahor/forex:98
        ports:
        - containerPort: 8080  # our app port
